import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FileText,
  Plus,
  Download,
  Send,
  Copy,
  Check,
  Trash2,
  RefreshCw,
  Search,
  PenLine,
  Eye,
  X,
  Clock,
  CheckCircle2,
  XCircle,
  Mail,
} from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Contract {
  id: string;
  booking_id: string | null;
  title: string;
  status: 'draft' | 'sent' | 'signed' | 'cancelled';
  guest_name: string | null;
  guest_email: string | null;
  sign_token: string;
  signed_at: string | null;
  sent_at: string | null;
  created_at: string;
  content: string | null;
}

interface BookingOption {
  id: string;
  guest_name: string;
  guest_email: string | null;
  guest_phone: string | null;
  start_date: string;
  end_date: string;
  total_price: number;
  currency: string;
  properties: { name: string; address?: string } | null;
}

const statusConfig = {
  draft:     { color: 'text-slate-400 bg-slate-800 border-slate-700', icon: <Clock className="w-3 h-3" /> },
  sent:      { color: 'text-blue-400 bg-blue-900/20 border-blue-800', icon: <Send className="w-3 h-3" /> },
  signed:    { color: 'text-emerald-400 bg-emerald-900/20 border-emerald-800', icon: <CheckCircle2 className="w-3 h-3" /> },
  cancelled: { color: 'text-red-400 bg-red-900/20 border-red-800', icon: <XCircle className="w-3 h-3" /> },
};

function generateContractText(booking: BookingOption, companyName = 'Triadak Property Management'): string {
  const nights = Math.ceil(
    (new Date(booking.end_date).getTime() - new Date(booking.start_date).getTime()) / (1000 * 60 * 60 * 24)
  );
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `RENTAL AGREEMENT

Date: ${today}

PARTIES
-------
Landlord/Manager: ${companyName}
Tenant/Guest: ${booking.guest_name}
Email: ${booking.guest_email || 'N/A'}

PROPERTY
--------
Property Name: ${booking.properties?.name || 'N/A'}
Address: ${booking.properties?.address || 'As provided at check-in'}

RENTAL PERIOD
-------------
Check-in:  ${booking.start_date}
Check-out: ${booking.end_date}
Duration:  ${nights} night${nights !== 1 ? 's' : ''}

FINANCIAL TERMS
---------------
Total Rental Price: ${booking.currency || 'EUR'} ${booking.total_price}
Payment Status: As per booking record

TERMS AND CONDITIONS
--------------------
1. OCCUPANCY: The property shall be occupied only by the registered guest(s). Subletting is not permitted.

2. CHECK-IN/CHECK-OUT: Guest agrees to arrive and depart at the agreed times. Late check-out may incur additional charges.

3. PROPERTY CARE: The guest agrees to take good care of the property and its contents, and to report any damage immediately.

4. PROHIBITED ACTIVITIES: Smoking, pets, parties, and events are prohibited unless explicitly agreed in writing.

5. NOISE: Guests agree to respect quiet hours (10pm–8am) and be considerate of neighbours.

6. CLEANING: The property must be left in a reasonably clean condition at checkout. A cleaning fee may apply.

7. DAMAGES: The guest is liable for any damage caused during the stay beyond normal wear and tear.

8. CANCELLATION: Cancellation policies are as stated at the time of booking.

9. LIABILITY: The landlord/manager is not responsible for loss or theft of personal belongings.

10. GOVERNING LAW: This agreement is governed by the applicable local laws.

SIGNATURES
----------
By signing below, both parties agree to the terms and conditions stated in this agreement.

Landlord/Manager: ___________________________   Date: ___________

Tenant/Guest: ______________________________   Date: ___________

---
This contract was generated by Triadak Property Management Platform.
Booking Reference: ${booking.id.slice(0, 8).toUpperCase()}`;
}

function downloadPdf(contract: Contract, booking: BookingOption | undefined) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('RENTAL AGREEMENT', margin, 20);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Ref: #${contract.id.slice(0, 8).toUpperCase()}`, pageWidth - margin, 20, { align: 'right' });

  y = 45;
  doc.setTextColor(30, 41, 59);

  if (booking) {
    // Parties table
    autoTable(doc, {
      startY: y,
      head: [['PARTIES', '']],
      body: [
        ['Guest', booking.guest_name],
        ['Email', booking.guest_email || 'N/A'],
        ['Property', booking.properties?.name || 'N/A'],
      ],
      theme: 'grid',
      headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold', fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 } },
      margin: { left: margin, right: margin },
    });
    y = (doc as any).lastAutoTable.finalY + 8;

    // Dates table
    const nights = Math.ceil(
      (new Date(booking.end_date).getTime() - new Date(booking.start_date).getTime()) / (1000 * 60 * 60 * 24)
    );
    autoTable(doc, {
      startY: y,
      head: [['RENTAL PERIOD', '']],
      body: [
        ['Check-in', booking.start_date],
        ['Check-out', booking.end_date],
        ['Duration', `${nights} night${nights !== 1 ? 's' : ''}`],
        ['Total Price', `${booking.currency || 'EUR'} ${booking.total_price}`],
      ],
      theme: 'grid',
      headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold', fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 } },
      margin: { left: margin, right: margin },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // Terms
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('TERMS AND CONDITIONS', margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);

  const terms = [
    '1. OCCUPANCY: The property shall be occupied only by registered guest(s). Subletting is not permitted.',
    '2. CHECK-IN/CHECK-OUT: Guest agrees to arrive and depart at the agreed times.',
    '3. PROPERTY CARE: Guest agrees to take good care of the property and report any damage immediately.',
    '4. PROHIBITED: Smoking, pets, parties and events are prohibited unless explicitly agreed in writing.',
    '5. NOISE: Guests agree to respect quiet hours (10pm–8am) and be considerate of neighbours.',
    '6. CLEANING: Property must be left in a reasonably clean condition at checkout.',
    '7. DAMAGES: The guest is liable for any damage caused during the stay beyond normal wear and tear.',
    '8. CANCELLATION: Cancellation policies are as stated at the time of booking.',
    '9. LIABILITY: The landlord is not responsible for loss or theft of personal belongings.',
    '10. GOVERNING LAW: This agreement is governed by applicable local laws.',
  ];

  terms.forEach((term) => {
    const lines = doc.splitTextToSize(term, pageWidth - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 1;
  });

  // Signature block
  y += 8;
  doc.setDrawColor(203, 213, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('SIGNATURES', margin, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);

  if (contract.status === 'signed' && contract.signature) {
    doc.text(`Tenant/Guest: ${contract.signature}`, margin, y);
    y += 5;
    doc.text(`Signed on: ${new Date(contract.signed_at!).toLocaleDateString()}`, margin, y);
  } else {
    doc.text('Landlord/Manager: _______________________________   Date: ____________', margin, y);
    y += 10;
    doc.text('Tenant/Guest: __________________________________   Date: ____________', margin, y);
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Triadak Property Management Platform · triadak.io', pageWidth / 2, footerY, { align: 'center' });

  doc.save(`contract-${contract.id.slice(0, 8)}.pdf`);
}

export default function Contracts() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const [contracts, setContracts] = useState<Contract[]>([]);
  const [bookings, setBookings] = useState<BookingOption[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [selectedBookingId, setSelectedBookingId] = useState('');
  const [generating, setGenerating] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [previewContract, setPreviewContract] = useState<Contract | null>(null);

  useEffect(() => { loadData(); }, []);

  async function loadData() {
    setLoading(true);
    try {
      const [{ data: contractsData }, { data: bookingsData }] = await Promise.all([
        supabase.from('contracts').select('*').order('created_at', { ascending: false }),
        supabase.from('bookings').select('id, guest_name, guest_email, guest_phone, start_date, end_date, total_price, currency, properties(name)').order('start_date', { ascending: false }).limit(100),
      ]);
      setContracts((contractsData || []) as Contract[]);
      setBookings((bookingsData || []) as any);
    } catch (err) {
      console.error(err);
    }
    setLoading(false);
  }

  async function handleGenerate() {
    if (!selectedBookingId || !user) return;
    setGenerating(true);
    try {
      const booking = bookings.find(b => b.id === selectedBookingId);
      if (!booking) throw new Error('Booking not found');

      const content = generateContractText(booking);
      const { error } = await supabase.from('contracts').insert({
        booking_id: booking.id,
        property_id: null,
        user_id: user.id,
        title: `${t('contracts.contractTitle')} — ${booking.guest_name}`,
        content,
        status: 'draft',
        guest_name: booking.guest_name,
        guest_email: booking.guest_email,
      });
      if (error) throw error;
      setShowModal(false);
      setSelectedBookingId('');
      await loadData();
    } catch (err: any) {
      alert(err.message);
    }
    setGenerating(false);
  }

  async function copySignLink(contract: Contract) {
    const url = `${window.location.origin}/contract/${contract.sign_token}`;
    await navigator.clipboard.writeText(url);
    setCopiedId(contract.id);

    // Mark as sent if still draft
    if (contract.status === 'draft') {
      await supabase.from('contracts').update({ status: 'sent', sent_at: new Date().toISOString() }).eq('id', contract.id);
      await loadData();
    }
    setTimeout(() => setCopiedId(null), 2500);
  }

  async function handleDelete(id: string) {
    if (!confirm(t('contracts.confirmDelete'))) return;
    setDeletingId(id);
    await supabase.from('contracts').delete().eq('id', id);
    setDeletingId(null);
    await loadData();
  }

  function getBookingForContract(contract: Contract): BookingOption | undefined {
    return bookings.find(b => b.id === contract.booking_id);
  }

  const filtered = contracts.filter(c =>
    !search ||
    c.guest_name?.toLowerCase().includes(search.toLowerCase()) ||
    c.title.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <FileText className="w-7 h-7 text-violet-400" />
            {t('contracts.title')}
          </h1>
          <p className="text-slate-400 mt-1">{t('contracts.subtitle')}</p>
        </div>
        <div className="flex gap-3">
          <button onClick={loadData} className="px-4 py-2 rounded-xl bg-slate-700 hover:bg-slate-600 text-slate-300 transition flex items-center gap-2">
            <RefreshCw className="w-4 h-4" />
          </button>
          <button
            onClick={() => setShowModal(true)}
            className="px-5 py-2.5 rounded-xl bg-violet-600 hover:bg-violet-500 text-white font-medium transition flex items-center gap-2"
          >
            <Plus className="w-4 h-4" />
            {t('contracts.newContract')}
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {(['draft', 'sent', 'signed', 'cancelled'] as const).map((status) => {
          const count = contracts.filter(c => c.status === status).length;
          const cfg = statusConfig[status];
          return (
            <motion.div key={status} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
              className="bg-slate-800/60 border border-slate-700 rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <span className="text-slate-400 text-sm capitalize">{t(`contracts.status.${status}`)}</span>
                <span className={`flex items-center gap-1 text-xs px-2 py-0.5 rounded-full border ${cfg.color}`}>
                  {cfg.icon}
                </span>
              </div>
              <p className="text-2xl font-bold text-white">{count}</p>
            </motion.div>
          );
        })}
      </div>

      {/* Search */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
        <input
          type="text"
          value={search}
          onChange={e => setSearch(e.target.value)}
          placeholder={`${t('common.search')}...`}
          className="w-full pl-9 pr-4 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-violet-500/50"
        />
      </div>

      {/* Contracts List */}
      {loading ? (
        <div className="flex items-center justify-center h-48">
          <RefreshCw className="w-8 h-8 text-violet-400 animate-spin" />
        </div>
      ) : filtered.length === 0 ? (
        <div className="bg-slate-800/60 border border-slate-700 rounded-xl p-12 text-center">
          <FileText className="w-12 h-12 text-slate-600 mx-auto mb-3" />
          <p className="text-slate-400 font-medium">{t('contracts.noContracts')}</p>
          <p className="text-slate-500 text-sm mt-1">{t('contracts.noContractsDesc')}</p>
          <button
            onClick={() => setShowModal(true)}
            className="mt-4 px-5 py-2.5 rounded-xl bg-violet-600 hover:bg-violet-500 text-white font-medium transition flex items-center gap-2 mx-auto"
          >
            <Plus className="w-4 h-4" /> {t('contracts.newContract')}
          </button>
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map((contract) => {
            const booking = getBookingForContract(contract);
            const cfg = statusConfig[contract.status] || statusConfig.draft;
            return (
              <motion.div
                key={contract.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-slate-800/60 border border-slate-700 rounded-xl p-4 flex flex-col sm:flex-row sm:items-center gap-4"
              >
                <div className="flex items-center gap-3 flex-1 min-w-0">
                  <div className="w-10 h-10 rounded-xl bg-violet-900/30 border border-violet-800/50 flex items-center justify-center shrink-0">
                    <FileText className="w-5 h-5 text-violet-400" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-white font-medium truncate">{contract.title}</p>
                    <div className="flex items-center gap-2 mt-0.5 flex-wrap">
                      {contract.guest_email && (
                        <span className="text-slate-500 text-xs flex items-center gap-1">
                          <Mail className="w-3 h-3" />{contract.guest_email}
                        </span>
                      )}
                      {booking && (
                        <span className="text-slate-500 text-xs">{booking.start_date} → {booking.end_date}</span>
                      )}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-3 flex-wrap sm:shrink-0">
                  <span className={`flex items-center gap-1 text-xs px-2.5 py-1 rounded-full border font-medium ${cfg.color}`}>
                    {cfg.icon} {t(`contracts.status.${contract.status}`)}
                  </span>

                  {contract.status === 'signed' && contract.signed_at && (
                    <span className="text-xs text-emerald-400">
                      {t('contracts.signedOn')} {new Date(contract.signed_at).toLocaleDateString()}
                    </span>
                  )}

                  {/* Actions */}
                  <div className="flex items-center gap-1.5">
                    <button
                      onClick={() => setPreviewContract(contract)}
                      title={t('contracts.preview')}
                      className="p-2 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-300 transition"
                    >
                      <Eye className="w-4 h-4" />
                    </button>
                    <button
                      onClick={() => downloadPdf(contract, booking)}
                      title={t('contracts.download')}
                      className="p-2 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-300 transition"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                    {contract.status !== 'signed' && contract.status !== 'cancelled' && (
                      <button
                        onClick={() => copySignLink(contract)}
                        title={t('contracts.copyLink')}
                        className="p-2 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-300 transition"
                      >
                        {copiedId === contract.id ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                      </button>
                    )}
                    <button
                      onClick={() => handleDelete(contract.id)}
                      disabled={deletingId === contract.id}
                      title={t('contracts.deleteContract')}
                      className="p-2 rounded-lg bg-slate-700 hover:bg-red-900/40 text-slate-400 hover:text-red-400 transition"
                    >
                      {deletingId === contract.id ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Trash2 className="w-4 h-4" />}
                    </button>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      )}

      {/* Generate Modal */}
      <AnimatePresence>
        {showModal && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4"
            onClick={() => setShowModal(false)}
          >
            <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
              onClick={e => e.stopPropagation()}
              className="bg-slate-800 border border-slate-700 rounded-2xl w-full max-w-md p-6"
            >
              <div className="flex justify-between items-center mb-5">
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                  <PenLine className="w-5 h-5 text-violet-400" />
                  {t('contracts.generateFromBooking')}
                </h3>
                <button onClick={() => setShowModal(false)} className="text-slate-400 hover:text-white">
                  <X className="w-5 h-5" />
                </button>
              </div>

              <label className="text-sm text-slate-400 mb-2 block">{t('contracts.selectBooking')}</label>
              <select
                value={selectedBookingId}
                onChange={e => setSelectedBookingId(e.target.value)}
                className="w-full px-4 py-3 rounded-xl bg-slate-700 border border-slate-600 text-white focus:outline-none focus:ring-2 focus:ring-violet-500/50 mb-5"
              >
                <option value="">{t('contracts.chooseBooking')}</option>
                {bookings.map(b => (
                  <option key={b.id} value={b.id}>
                    {b.guest_name} — {(b.properties as any)?.name || 'Property'} ({b.start_date})
                  </option>
                ))}
              </select>

              <button
                onClick={handleGenerate}
                disabled={!selectedBookingId || generating}
                className="w-full py-3 rounded-xl bg-violet-600 hover:bg-violet-500 text-white font-semibold transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {generating ? <RefreshCw className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
                {generating ? t('contracts.generating') : t('contracts.generateFromBooking')}
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Preview Modal */}
      <AnimatePresence>
        {previewContract && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4"
            onClick={() => setPreviewContract(null)}
          >
            <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
              onClick={e => e.stopPropagation()}
              className="bg-slate-800 border border-slate-700 rounded-2xl w-full max-w-2xl max-h-[85vh] flex flex-col"
            >
              <div className="flex justify-between items-center p-5 border-b border-slate-700">
                <h3 className="text-lg font-bold text-white">{previewContract.title}</h3>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => downloadPdf(previewContract, getBookingForContract(previewContract))}
                    className="px-3 py-1.5 rounded-lg bg-violet-600 hover:bg-violet-500 text-white text-sm flex items-center gap-1.5 transition"
                  >
                    <Download className="w-4 h-4" /> {t('contracts.download')}
                  </button>
                  <button onClick={() => setPreviewContract(null)} className="text-slate-400 hover:text-white p-1">
                    <X className="w-5 h-5" />
                  </button>
                </div>
              </div>
              <div className="overflow-y-auto p-5 flex-1">
                <pre className="text-slate-300 text-sm whitespace-pre-wrap font-mono leading-relaxed bg-slate-900/50 rounded-xl p-4">
                  {previewContract.content || ''}
                </pre>
                {previewContract.status === 'signed' && previewContract.signature && (
                  <div className="mt-4 bg-emerald-900/20 border border-emerald-800 rounded-xl p-4">
                    <p className="text-emerald-400 text-sm font-medium flex items-center gap-2">
                      <CheckCircle2 className="w-4 h-4" />
                      {t('contracts.signedOn')} {new Date(previewContract.signed_at!).toLocaleString()}
                    </p>
                    <p className="text-slate-300 mt-1">
                      {t('contracts.signPage.signedBy')}: <span className="font-semibold">{previewContract.signature}</span>
                    </p>
                  </div>
                )}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
